{{ if eq .Values.rosa_env "dev" }}
{{- range $key, $value := .Values.apigroups }}
{{- range $namespacePattern := $.Values.namespace_patterns }}
{{ if eq  $namespacePattern "dev-%s-app" }}
{{ if eq ( $value.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-viewer
  namespace: {{ printf $namespacePattern $value.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "3" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-viewer
subjects:
  - kind: ServiceAccount
    name: image-pull
    namespace: {{ printf $namespacePattern $value.name | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}